### ISSUE TITLE
Constitution has unclear terms

### ISSUE THREAD

**Issue by andrewthebold** [stanfordaigroup/stanfordai.group#2]
Checkout [this clause of the constitution](https://github.com/stanfordaigroup/stanfordai.group/blob/master/src/pages/constitution/index.md#section-b-election-procedure-and-length-of-term).

> Any member who has received 3 nominations from new or returning members can become a project leader through the unanimous **(majority?)** approval of the board.

Emphasis mine. We should fix this @junwonpk

**Comment by andrewsoohwanlee** [comment]
Closed with #4

**Comment by andrewthebold** [comment]
Closed with #4
